sharding:
  jdbc:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.151.128:3306/demo_ds?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.151.129:3306/demo_ds?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
    config:
      sharding:
#        tables:
#          t_order:
#            key-generator-column-name: id
        props:
          sql:
            show: true
      masterslave:
        name: ds_ms
        master-data-source-name: ds0
        slave-data-source-names: ds1
        load-balance-algorithm-class-name: springboot.sharding.balance.NewBananceAlgorithm