sharding:
  jdbc:
    datasource:
      names: ds0,ds1,ds2,ds3
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.151.128:3306/ds_0?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.151.128:3306/ds_1?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.151.129:3306/ds_0?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
      ds3:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.151.129:3306/ds_1?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
    config:
      sharding:
        default-database-strategy:
          inline:
            sharding-column: order_id
            algorithm-expression: ds$->{order_id % 2}
        tables:
          t_order:
            actualDataNodes: ds${0..1}.t_order${0..1}
            tableStrategy:
              inline:
                shardingColumn: order_id
                algorithmExpression: t_order${order_id % 2}
            keyGeneratorColumnName: order_id
        master-slave-rules:
         ms_ds0:
           master-data-source-name: ds0
           slave-data-source-names: ds2
           load-balance-algorithm-type: ROUND_ROBIN
         ms_ds1:
           masterDataSourceName: ds1
           slaveDataSourceNames: ds3
           load-balance-algorithm-class-name: springboot.sharding.balance.NewBananceAlgorithm
        props:
          sql:
            show: true
#        master-slave-rules:
#          ms_ds0:
#            master-data-source-name: ds0
#            slave-data-source-names: ds2
#            load-balance-algorithm-type: round_robin
#          ms_ds1:
#            master-data-source-name: ds1
#            slave-data-source-names: ds3
#            load-balance-algorithm-class-name: springboot.sharding.balance.NewBananceAlgorithm
