logging:
  level:
    ROOT: INFO
    shardingsphere.demo: DEBUG
    shardingsphere.demo.mapper: debug
server:
  port: 8100
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: shardingsphere.demo.entity
#  config-location: classpath:mybatis-config.xml

#spring:
#  profiles:
#    active: sharding
sharding:
  jdbc:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.151.128:3306/demo_ds_0?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456

      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.151.128:3306/demo_ds_1?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
    config:
      sharding:
        default-database-strategy:
          standard:
            precise-algorithm-class-name: springboot.sharding.strategy.HashCodePreciseShardingAlgorithm
            sharding-column: user_id
        tables:
          t_order:
            actual-data-nodes: ds$->{0..1}.t_order
            table-strategy:
              standard:
                precise-algorithm-class-name: springboot.sharding.strategy.HashCodePreciseShardingAlgorithm
                sharding-column: order_id
#            key-generator-column-name: id
          t_order_item:
            actual-data-nodes: ds$->{0..1}.t_order_item
            table-strategy:
              standard:
                precise-algorithm-class-name: springboot.sharding.strategy.HashCodePreciseShardingAlgorithm
                sharding-column: order_item_id
#            key-generator-column-name: id